### ISSUE TITLE
Registration of the research.fi ontology

### ISSUE THREAD

**Issue by chenejac** [CSCfi/mscr-ui-monorepo#233]
The [TTV](https://tietomallit.beta.yti.cloud.dvv.fi/model/ttv) ontology can't be registered properly as a Schema. There is only ROOT element, other elements might be loaded, but labels of classes and properties are not displayed. 

# Steps to reproduce

- Export and download the turtle representation of https://tietomallit.beta.yti.cloud.dvv.fi/model/ttv
- Log in at https://mscr-test.2.rahtiapp.fi/
- Click at Schemas
- Create new Schema, fill the form and upload previously downloaded ttl file (step 1)
- [Schema](https://mscr-test.2.rahtiapp.fi/schema/mscr:schema:711f4d19-564c-4bc8-b674-20f9349ff6fe) is created, includes ROOT element and some subelements, but we can't see any labels

**Comment by maariaw** [comment]
Thank you for reporting the issue.
I did some preliminary testing, and I seem to get the best result by registering the schema in SHACL format: https://mscr-test.2.rahtiapp.fi/schema/mscr:schema:ebc40c0f-8aae-4e9a-b88a-34779c5b243d
If you try that, does the schema look like it should?

**Comment by chenejac** [comment]
@maariaw thanks for prompt response. 

Yes, it works if SHACL is selected.

**Comment by maariaw** [comment]
Good to hear! I'll close this issue then, don't hesitate to open another if you run into more problems.
